=== briesenberg07/XML-XSL-HTML-Ogham-info/XMLandXSD/oghamSchemaV0_11.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="oghamBase">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="about">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="title"/>
                            <xs:element name="author"/>
                            <xs:element ref="description"/>
                            <xs:element minOccurs="0" ref="sources"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="oghamCharacters">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ogham" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="letter"/>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            ref="altLetter"/>
                                        <xs:element name="unicodeCharacter"/>
                                        <xs:element maxOccurs="unbounded" ref="pronunciation"/>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            ref="meaning"/>
                                        <xs:element ref="series"/>
                                        <xs:element ref="verseBríatharogamMorainnmacMoín"
                                            minOccurs="0"/>
                                        <xs:element ref="verseBríatharogamMaicindÓc" minOccurs="0"/>
                                        <xs:element minOccurs="0" ref="verseBríatharogamConCulainn"/>
                                        <xs:element ref="image" maxOccurs="unbounded"/>
                                        <xs:element name="unicode"/>
                                        <xs:element minOccurs="0" ref="description"/>
                                        <xs:element ref="sources"/>
                                    </xs:sequence>
                                    <xs:attribute ref="id" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sourceDefs">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sourceDef" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="title"/>
                                        <xs:element ref="shortDescription"/>
                                        <xs:element ref="url"/>
                                    </xs:sequence>
                                    <xs:attribute ref="id" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="outieSeriesIndex">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="indexSeries">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="seriesName"/>
                                        <xs:element maxOccurs="unbounded" ref="oghamIdRef"/>
                                    </xs:sequence>
                                    <xs:attribute ref="id" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="recursiveOutieHierarchy">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="category"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sequences">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="sequence">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="description"/>
                                        <xs:element maxOccurs="unbounded" ref="oghamIdRef"/>
                                        <xs:element ref="sources"/>
                                    </xs:sequence>
                                    <xs:attribute name="seqTitle"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:attribute name="id" type="xs:ID"/>
    <xs:element name="image">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="imageOrientation">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="horizontal"/>
                                <xs:enumeration value="vertical"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="verseBríatharogamMorainnmacMoín">
        <xs:complexType mixed="true">
            <xs:group ref="inline"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="verseBríatharogamMaicindÓc">
        <xs:complexType mixed="true">
            <xs:group ref="inline"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="verseBríatharogamConCulainn">
        <xs:complexType mixed="true">
            <xs:group ref="inline"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="series">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Aicme Beithe"/>
                <xs:enumeration value="Aicme hÚatha"/>
                <xs:enumeration value="Aicme Muine"/>
                <xs:enumeration value="Aicme Ailme"/>
                <xs:enumeration value="forfeda"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="pronunciation">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="language">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="Old Irish"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="altLetter"/>
    <xs:element name="letter"/>
    <xs:element name="sources">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="sourceIdRef" type="xs:IDREF"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:group name="inline">
        <xs:choice>
            <xs:element minOccurs="0" ref="b"/>
            <xs:element minOccurs="0" ref="i"/>
            <xs:element minOccurs="0" ref="u"/>
            <xs:element minOccurs="0" ref="xref"/>
            <xs:element minOccurs="0" name="pubMentioned"/>
        </xs:choice>
    </xs:group>
    <xs:group name="block">
        <xs:choice>
            <xs:element ref="p"/>
            <xs:element ref="ul"/>
            <xs:element ref="ol"/>
            <xs:element ref="br"/>
            <xs:element ref="table"/>
            <xs:element name="media">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="title"/>
                        <xs:element minOccurs="0" name="caption">
                            <xs:complexType>
                                <xs:group ref="inline"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute ref="id" use="required"/>
                    <xs:attribute name="url" type="xs:string" use="required"/>
                    <xs:attribute name="type" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:NMTOKEN"/>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="style" type="xs:string"/>
                </xs:complexType>
            </xs:element>
            <xs:element ref="editor"/>
        </xs:choice>
    </xs:group>
    <xs:element name="description">
        <xs:complexType mixed="true">
            <xs:group maxOccurs="unbounded" ref="block"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="meaning">
        <xs:complexType mixed="true">
            <xs:attribute ref="meaningType" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="arborealTradition"/>
    <xs:element name="shortDescription"/>
    <xs:element name="url"/>
    <xs:element name="title"> </xs:element>
    <xs:element name="category">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element minOccurs="0" ref="description"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="oghamMeaningIdRef">
                    <xs:complexType>
                        <xs:attribute ref="meaningType" use="required"/>
                        <xs:attribute name="idRef" type="xs:IDREF" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="category"/>
            </xs:sequence>
            <xs:attribute ref="id" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="indexedMeaning">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="wordOrPhrase">
                    <xs:complexType mixed="true">
                        <xs:group minOccurs="0" ref="inline"/>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" name="oghamRefId" type="xs:IDREF"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:attribute name="meaningType">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="botanicalTrees"/>
                <xs:enumeration value="botanicalOtherPlants"/>
                <xs:enumeration value="otherAbstractThings"/>
                <xs:enumeration value="otherConcreteThings"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:element name="p">
        <xs:complexType mixed="true">
            <xs:group ref="inline" maxOccurs="unbounded" minOccurs="0"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ul">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="li"/>
                <xs:element ref="ul"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="ol">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element maxOccurs="unbounded" ref="li"/>
                <xs:element minOccurs="0" ref="ol"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="b"/>
    <xs:element name="i"/>
    <xs:element name="u"/>
    <xs:element name="xref">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="xrefText">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hotText"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute ref="id" use="required"/>
            <xs:attribute name="type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:NMTOKEN"/>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="dest" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="li">
        <xs:complexType mixed="true">
            <xs:group maxOccurs="unbounded" minOccurs="0" ref="inline"/>
        </xs:complexType>
    </xs:element>
    <xs:element fixed="" name="br" nillable="true"/>
    <xs:element name="table">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="0">
                <xs:element maxOccurs="unbounded" name="tr">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="td">
                                <xs:complexType>
                                    <xs:choice maxOccurs="unbounded">
                                        <xs:group ref="block"/>
                                    </xs:choice>
                                    <xs:attribute name="style" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="style" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="border" type="xs:string"/>
            <xs:attribute name="cellSpacing" type="xs:string"/>
            <xs:attribute name="cellPadding" type="xs:string"/>
            <xs:attribute name="style" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="editor">
        <xs:complexType>
            <xs:attribute name="showEdits" type="xs:boolean"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="relatedOghamChars">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="description"/>
                <xs:element minOccurs="0" ref="image"/>
                <xs:element maxOccurs="unbounded" ref="oghamIdRef"/>
                <xs:element ref="sources"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="oghamIdRef" type="xs:IDREF"/>
</xs:schema>

=== briesenberg07/XML-XSL-HTML-Ogham-info/XMLandXSD/oghamInstanceV0_11.xml
<?xml version="1.0" encoding="UTF-8"?>
<oghamBase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="oghamSchemaV0_11.xsd">
    <about>
        <title>Ogham Information, Version 0.1</title>
        <author>Benjamin M. Riesenberg</author>
        <description>
            <p> I created this site as a project for the <b>Technical Foundations of Information</b>
                course at the University of Washington iSchool. I had a couple of goals: </p>
            <ol>
                <li>Learn about XML and using XML to organize information and create a
                    publication--in this case a website</li>
                <li>Learn more about the ogham characters and present it in a clear and precise
                    way</li>
            </ol>
            <p> I succeeded in the first task to some extent. Regarding the second task, I do
                present some information here, but let me be clear: </p>
            <p> THE INFORMATION PRESENTED HERE HAS BEEN TAKEN DIRECTLY FROM THE WIKIPEDIA PAGES CITED BELOW, AND POURED INTO THE FORM YOU SEE HERE FOR THE PURPOSE OF LEARNING HOW TO USE XML SCHEMAS, INSTANCES, AND TRANSFORMS. </p>
            <p> I had hoped to spend some time reading The Scholars' Primer--cited below both from
                the Internet Archive and the Hathi Trust--and to present the information about
                characters based on my close reading of this text. I should have known that I'd be
                more than busy enough learning about XML and wouldn't have time for this. I will say
                here that I understand that book to be a significant source on the ogham characters.
                If I understand correctly, it summarizes a lot of what is known about the characters
                based on manuscripts and other sources, and is where much of what I found at
                Wikipedia came from. </p>
        </description>
        <sources>
            <sourceIdRef>oghamWiki</sourceIdRef>
            <sourceIdRef>briatharogamWiki</sourceIdRef>
            <sourceIdRef>oghamWikiCommons</sourceIdRef>
            <sourceIdRef>oghamUnicodeWiki</sourceIdRef>
            <sourceIdRef>auraiceptInternetArchive</sourceIdRef>
            <sourceIdRef>auraiceptHathiTrust</sourceIdRef>
        </sources>
    </about>
    <oghamCharacters>
        <ogham id="_B">
            <letter>B</letter>
            <unicodeCharacter>ᚁ</unicodeCharacter>
            <pronunciation>Beith</pronunciation>
            <pronunciation language="Old Irish">Beithe</pronunciation>
            <meaning meaningType="botanicalTrees">Birch</meaning>
            <series>Aicme Beithe</series>
            <verseBríatharogamMorainnmacMoín><i>Féochos foltchain</i>: "Withered foot with fine
                hair"</verseBríatharogamMorainnmacMoín>
            <verseBríatharogamMaicindÓc><i>Glaisem cnis</i>: "Greyest of
                skin"</verseBríatharogamMaicindÓc>
            <verseBríatharogamConCulainn><i>Maise malach</i>: "Beauty of the
                eyebrow"</verseBríatharogamConCulainn>
            <image imageOrientation="horizontal">Ogham_letter_beith.svg</image>
            <image imageOrientation="vertical">Ogham_vertical_letter_beith.svg</image>
            <unicode>1681</unicode>
            <description>
                <p>So, to be honest, I <i>don't have</i> content that actually needs to be in this
                    description element right now. I can, however, think of a few things that might
                    be good to include if I had them:</p>
                <ul>
                    <li>Some fun facts. But they'd have to be <b>fun</b>.</li>
                    <li>Some other sort of notes or somesuch. Something that <u>isn't included
                            elsewhere</u>.</li>
                    <li>Other stuff I can't think of right now.</li>
                </ul>
                <br/>
                <p>Let me say a little more--I hope that I'll be able to use this kind of rich
                    description element along with it's child elements in the future.</p>
            </description>
            <sources>
                <sourceIdRef>oghamWiki</sourceIdRef>
                <sourceIdRef>briatharogamWiki</sourceIdRef>
                <sourceIdRef>oghamWikiCommons</sourceIdRef>
                <sourceIdRef>oghamUnicodeWiki</sourceIdRef>
            </sources>
        </ogham>
        <ogham id="_L">
            <letter>L</letter>
            <unicodeCharacter>ᚂ</unicodeCharacter>
            <pronunciation>Luis</pronunciation>
            <meaning meaningType="botanicalTrees">Rowan</meaning>
            <series>Aicme Beithe</series>
            <verseBríatharogamMorainnmacMoín><i>Lí súla</i>: "Lustre of the
                eye"</verseBríatharogamMorainnmacMoín>
            <verseBríatharogamMaicindÓc><i>Carae cethrae</i>: "Friend of
                cattle"</verseBríatharogamMaicindÓc>
            <verseBríatharogamConCulainn><i>Lúth cethrae</i>: "Sustenance of
                cattle"</verseBríatharogamConCulainn>
            <image imageOrientation="horizontal">Ogham_letter_luis.svg</image>
            <image imageOrientation="vertical">Ogham_vertical_letter_luis.svg</image>
            <unicode>1682</unicode>
            <sources>
                <sourceIdRef>oghamWiki</sourceIdRef>
                <sourceIdRef>briatharogamWiki</sourceIdRef>
                <sourceIdRef>oghamWikiCommons</sourceIdRef>
                <sourceIdRef>oghamUnicodeWiki</sourceIdRef>
            </sources>
        </ogham>
        <ogham id="_F">
            <letter>F</letter>
            <unicodeCharacter>ᚃ</unicodeCharacter>
            <pronunciation>Fearn</pronunciation>
            <meaning meaningType="botanicalTrees">Alder</meaning>
            <series>Aicme Beithe</series>
            <verseBríatharogamMorainnmacMoín><i>Airenach fían</i>: "Vanguard of
                warriors"</verseBríatharogamMorainnmacMoín>
            <verseBríatharogamMaicindÓc><i>Comét lachta</i>: "Milk
                container"</verseBríatharogamMaicindÓc>
            <verseBríatharogamConCulainn><i>Dín cridi</i>: "Protection of the
                heart"</verseBríatharogamConCulainn>
            <image imageOrientation="horizontal">Ogham_letter_fearn.svg</image>
            <image imageOrientation="vertical">Ogham_vertical_letter_fearn.svg</image>
            <unicode>1683</unicode>
            <sources>
                <sourceIdRef>oghamWiki</sourceIdRef>
                <sourceIdRef>briatharogamWiki</sourceIdRef>
                <sourceIdRef>oghamWikiCommons</sourceIdRef>
                <sourceIdRef>oghamUnicodeWiki</sourceIdRef>
            </sources>
        </ogham>
        <ogham id="_S">
            <letter>S</letter>
            <unicodeCharacter>ᚄ</unicodeCharacter>
            <pronunciation>Sail</pronunciation>
            <meaning meaningType="botanicalTrees">Willow</meaning>
            <series>Aicme Beithe</series>
            <verseBríatharogamMorainnmacMoín><i>Lí ambi</i>: "Pallor of a lifeless
                one"</verseBríatharogamMorainnmacMoín>
            <verseBríatharogamMaicindÓc><i>Lúth bech</i>: "Sustenance of
                bees"</verseBríatharogamMaicindÓc>
            <verseBríatharogamConCulainn><i>Tosach mela</i>: "Beginning of
                honey"</verseBríatharogamConCulainn>
            <image imageOrientation="horizontal">Ogham_letter_sail.svg</image>
            <image imageOrientation="vertical">Ogham_vertical_letter_sail.svg</image>
            <unicode>1684</unicode>
            <sources>
                <sourceIdRef>oghamWiki</sourceIdRef>
                <sourceIdRef>briatharogamWiki</sourceIdRef>
                <sourceIdRef>oghamWikiCommons</sourceIdRef>
                <sourceIdRef>oghamUnicodeWiki</sourceIdRef>
            </sources>
        </ogham>
        <ogham id="_N">
            <letter>N</letter>
            <unicodeCharacter>ᚅ</unicodeCharacter>
            <pronunciation>Nion</pronunciation>
            <pronunciation language="Old Irish">Nin</pronunciation>
            <meaning meaningType="botanicalTrees">Ash</meaning>
            <series>Aicme Beithe</series>
            <verseBríatharogamMorainnmacMoín><i>Costud side</i>: "Establishing of
                peace"</verseBríatharogamMorainnmacMoín>
            <verseBríatharogamMaicindÓc><i>Bág ban</i>: "Boast of
                women"</verseBríatharogamMaicindÓc>
            <verseBríatharogamConCulainn><i>Bág maise</i>: "Boast of
                beauty"</verseBríatharogamConCulainn>
            <image imageOrientation="horizontal">Ogham_letter_nion.svg</image>
            <image imageOrientation="vertical">Ogham_vertical_letter_nion.svg</image>
            <unicode>1685</unicode>
            <sources>
                <sourceIdRef>oghamWiki</sourceIdRef>
                <sourceIdRef>briatharogamWiki</sourceIdRef>
                <sourceIdRef>oghamWikiCommons</sourceIdRef>
                <sourceIdRef>oghamUnicodeWiki</sourceIdRef>
            </sources>
        </ogham>
        <ogham id="_H">
            <letter>H</letter>
            <unicodeCharacter>ᚆ</unicodeCharacter>
            <pronunciation>Uath</pronunciation>
            <pronunciation language="Old Irish">Úath</pronunciation>
            <meaning meaningType="otherAbstractThings">Horror</meaning>
            <meaning meaningType="otherAbstractThings">Fear</meaning>
            <meaning meaningType="botanicalTrees">White-thorn</meaning>
            <series>Aicme hÚatha</series>
            <verseBríatharogamMorainnmacMoín><i>Condál cúan</i>: "Assembly of packs of
                hounds"</verseBríatharogamMorainnmacMoín>
            <verseBríatharogamMaicindÓc><i>Bánad gnúise</i>: "Blanching of
                faces"</verseBríatharogamMaicindÓc>
            <verseBríatharogamConCulainn><i>Ansam aidche</i>: "Most difficult at
                night"</verseBríatharogamConCulainn>
